#!/usr/bin/env python3
"""
NetMon VM Registration Script
==============================
Registers a new VM guest device in NetMon, generates an agent token,
and outputs a ready-to-use agent configuration file.

Usage:
    python register_vm.py --name "Web Server 01" --server http://YOUR_SERVER:8000
    python register_vm.py --name "DB Server" --server http://YOUR_SERVER:8000 --location "Rack A3"
    python register_vm.py --name "App Server" --server http://YOUR_SERVER:8000 --output /tmp/agent.conf
    python register_vm.py --name "Test VM" --server http://YOUR_SERVER:8000 --format json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import textwrap
from pathlib import Path
from typing import Optional

try:
    import httpx
except ImportError:
    print("❌ httpx is required: pip install httpx")
    sys.exit(1)


def register_vm(
    server_url: str,
    name: str,
    location: Optional[str] = None,
    description: Optional[str] = None,
    timeout: int = 15,
) -> dict:
    """Register a new VM via NetMon API. Returns registration response."""
    url = f"{server_url.rstrip('/')}/api/agent/register"
    payload = {
        "name": name,
        "device_type": "vm_guest",
    }
    if location:
        payload["location"] = location
    if description:
        payload["description"] = description

    try:
        response = httpx.post(url, json=payload, timeout=timeout)
        if response.status_code == 200 or response.status_code == 201:
            return response.json()
        else:
            print(f"❌ Registration failed: HTTP {response.status_code}")
            print(f"   Response: {response.text}")
            sys.exit(1)
    except httpx.ConnectError:
        print(f"❌ Cannot connect to NetMon server at {server_url}")
        print("   Make sure the server is running and accessible.")
        sys.exit(1)
    except httpx.TimeoutException:
        print(f"❌ Connection timed out after {timeout}s")
        sys.exit(1)


def generate_config_ini(server_url: str, agent_token: str, poll_interval: int = 30) -> str:
    """Generate agent.conf INI content."""
    return textwrap.dedent(f"""\
        [agent]
        # NetMon Agent Configuration
        # Generated by register_vm.py
        # Server: {server_url}

        server_url = {server_url}
        agent_token = {agent_token}
        poll_interval = {poll_interval}
        request_timeout = 10
    """)


def generate_config_json(server_url: str, agent_token: str, poll_interval: int = 30) -> str:
    """Generate agent config as JSON."""
    return json.dumps({
        "server_url": server_url,
        "agent_token": agent_token,
        "poll_interval": poll_interval,
        "request_timeout": 10,
    }, indent=2)


def generate_linux_install_script(server_url: str, agent_token: str, poll_interval: int = 30) -> str:
    """Generate a one-liner install command for Linux."""
    return textwrap.dedent(f"""\
        # ── NetMon Linux Agent — Quick Install ──────────────────
        # Run this on the VM as root:
        
        curl -fsSL {server_url.rstrip('/')}/agents/linux/install.sh | \\
            sudo bash -s -- \\
            --server {server_url} \\
            --token {agent_token} \\
            --interval {poll_interval}
    """)


def generate_windows_install_script(server_url: str, agent_token: str, poll_interval: int = 30) -> str:
    """Generate a one-liner install command for Windows."""
    return textwrap.dedent(f"""\
        # ── NetMon Windows Agent — Quick Install ────────────────
        # Run this in PowerShell as Administrator:
        
        Set-ExecutionPolicy Bypass -Scope Process -Force; \\
        Invoke-WebRequest -Uri "{server_url.rstrip('/')}/agents/windows/install_service.ps1" -OutFile "$env:TEMP\\install_service.ps1"; \\
        & "$env:TEMP\\install_service.ps1" -ServerUrl "{server_url}" -AgentToken "{agent_token}" -PollInterval {poll_interval}
    """)


def main():
    parser = argparse.ArgumentParser(
        description="Register a new VM in NetMon and generate agent config",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              %(prog)s --name "Web Server" --server http://YOUR_SERVER:8000
              %(prog)s --name "DB Server" --server http://YOUR_SERVER:8000 --location "Rack A3"
              %(prog)s --name "App" --server http://YOUR_SERVER:8000 --output /tmp/agent.conf
              %(prog)s --name "Test" --server http://YOUR_SERVER:8000 --format json
        """),
    )
    parser.add_argument("--name", "-n", required=True, help="VM name (e.g., 'Web Server 01')")
    parser.add_argument("--server", "-s", required=True, help="NetMon server URL")
    parser.add_argument("--location", "-l", help="Physical/logical location")
    parser.add_argument("--description", "-d", help="Description")
    parser.add_argument("--interval", "-i", type=int, default=30, help="Polling interval (seconds)")
    parser.add_argument("--output", "-o", help="Output config file path (default: stdout)")
    parser.add_argument(
        "--format", "-f",
        choices=["ini", "json", "all"],
        default="ini",
        help="Config output format (default: ini)",
    )
    parser.add_argument("--quiet", "-q", action="store_true", help="Minimal output")

    args = parser.parse_args()

    if not args.quiet:
        print("╔══════════════════════════════════════════╗")
        print("║   NetMon VM Registration                ║")
        print("╚══════════════════════════════════════════╝")
        print()
        print(f"   Name:     {args.name}")
        print(f"   Server:   {args.server}")
        if args.location:
            print(f"   Location: {args.location}")
        print()

    # Register the VM
    result = register_vm(
        server_url=args.server,
        name=args.name,
        location=args.location,
        description=args.description,
    )

    agent_token = result.get("agent_token", "")
    device_id = result.get("device_id", "?")
    poll_interval = result.get("poll_interval", args.interval)

    if not args.quiet:
        print(f"✅ VM registered successfully!")
        print(f"   Device ID:    {device_id}")
        print(f"   Agent Token:  {agent_token[:12]}...{agent_token[-4:]}")
        print(f"   Poll Interval: {poll_interval}s")
        print()

    # Generate config
    if args.format == "ini":
        config_content = generate_config_ini(args.server, agent_token, poll_interval)
    elif args.format == "json":
        config_content = generate_config_json(args.server, agent_token, poll_interval)
    elif args.format == "all":
        config_content = (
            "# ── INI Format (agent.conf) ──\n"
            + generate_config_ini(args.server, agent_token, poll_interval)
            + "\n\n"
            + "# ── JSON Format ──\n"
            + generate_config_json(args.server, agent_token, poll_interval)
            + "\n\n"
            + "# ── Linux Install ──\n"
            + generate_linux_install_script(args.server, agent_token, poll_interval)
            + "\n\n"
            + "# ── Windows Install ──\n"
            + generate_windows_install_script(args.server, agent_token, poll_interval)
            + "\n"
        )
    else:
        config_content = generate_config_ini(args.server, agent_token, poll_interval)

    # Output
    if args.output:
        os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
        with open(args.output, "w") as f:
            f.write(config_content)
        if not args.quiet:
            print(f"📄 Config written to: {args.output}")
            print()
    else:
        if not args.quiet:
            print("── Agent Configuration ────────────────────")
        print(config_content)

    # Print install instructions
    if not args.quiet:
        print("── Quick Install ─────────────────────────")
        print()
        print("  Linux:")
        print(f"    curl -fsSL {args.server.rstrip('/')}/agents/linux/install.sh | \\")
        print(f"      sudo bash -s -- --server {args.server} --token {agent_token}")
        print()
        print("  Windows (PowerShell Admin):")
        print(f"    .\\install_service.ps1 -ServerUrl \"{args.server}\" -AgentToken \"{agent_token}\"")
        print()


if __name__ == "__main__":
    main()
